version: "3.9"
services:
  jsoncrack:
    image: jsoncrack
    labels:
      - dev.json.com=foo.local,bar.local
    container_name: json
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
